### ISSUE TITLE
Changing path only affects some URLs

### ISSUE THREAD

**Issue by danielfaulknor** [tildaslash/RatticWeb#226]
I've changed the webapp path to /someurl because it's behind a reverse proxy but only some URLs are changing.

See this Gist for the contents of the homepage, you can see that the assets pick up the URL fine, but nothing else does..
https://gist.github.com/danielfaulknor/1acb08cf912fe0f3c9c6

**Comment by EstebanMonge** [comment]
Hello I have the same problem.

I fixed with this steps:
Edit defaults.cfg and change:
urlroot = /
to 
urlroot = /rattic/

In Debian GNU/Linux 8.6 with Apache 2.4.10 put a file in /etc/apache2/sites-available/rattic.conf with this content:

Alias /rattic/robots.txt /opt/apps/RatticWeb/static/robots.txt
Alias /rattic/favicon.ico /opt/apps/RatticWeb/static/favicon.ico

AliasMatch ^/rattic/([^/]*\.css) /opt/apps/RatticWeb/static/styles/$1

Alias /rattic/media/ /opt/apps/RatticWeb/media/
Alias /rattic/static/ /opt/apps/RatticWeb/static/

<Directory /opt/apps/RatticWeb/static>
Require all granted
</Directory>

<Directory /opt/apps/RatticWeb/media>
Require all granted
</Directory>

WSGIScriptAlias / /opt/apps/RatticWeb/ratticweb/wsgi.py
WSGIPassAuthorization On

WSGIDaemonProcess rattic processes=2 threads=25 home=/opt/apps/RatticWeb/ python-path=/opt/apps/RatticWeb display-name=%{GROUP}
WSGIProcessGroup rattic


<Directory /opt/apps/RatticWeb/ratticweb>
  <Files wsgi.py>
        Require all granted
  </Files>
</Directory>
`

If you have a Python env:
`
Alias /rattic/robots.txt /opt/apps/RatticWeb/static/robots.txt
Alias /rattic/favicon.ico /opt/apps/RatticWeb/static/favicon.ico

AliasMatch ^/rattic/([^/]*\.css) /opt/apps/RatticWeb/static/styles/$1

Alias /rattic/media/ /opt/apps/RatticWeb/media/
Alias /rattic/static/ /opt/apps/RatticWeb/static/

<Directory /opt/apps/RatticWeb/static>
Require all granted
</Directory>

<Directory /opt/apps/RatticWeb/media>
Require all granted
</Directory>

WSGIPythonHome /opt/apps/RatticWeb
WSGIScriptAlias / /opt/apps/RatticWeb/ratticweb/wsgi.py
WSGIPassAuthorization On

WSGIDaemonProcess rattic processes=2 threads=25 home=/opt/apps/RatticWeb/ python-path=/opt/apps/RatticWeb display-name=%{GROUP}
WSGIProcessGroup rattic


<Directory /opt/apps/RatticWeb/ratticweb>
  <Files wsgi.py>
        Require all granted
  </Files>
</Directory>
`
